/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestion_projet;

import java.math.BigDecimal;
import model.HumanResource;

/**
 *
 * @author amadou
 */
public class New_RH extends javax.swing.JFrame  {

    /**
     * Creates new form New_RH
     */
    public New_RH() {
        super();
        
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_RH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_RH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_RH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_RH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Code = new javax.swing.JLabel();
        code_TF = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        label_TF = new javax.swing.JTextField();
        Initials_label = new javax.swing.JLabel();
        Initials_TF = new javax.swing.JTextField();
        Skrill_label = new javax.swing.JLabel();
        Capacity_label = new javax.swing.JLabel();
        Capacity_TF = new javax.swing.JTextField();
        Skrill_TF = new javax.swing.JTextField();
        allocation_label = new javax.swing.JLabel();
        allocation_TF = new javax.swing.JTextField();
        place_label = new javax.swing.JLabel();
        place_TF = new javax.swing.JTextField();
        Standard_label = new javax.swing.JLabel();
        Standrad_TF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Overtime_label = new javax.swing.JLabel();
        Overtime_TF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Use_label = new javax.swing.JLabel();
        Use_TF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Target_label = new javax.swing.JLabel();
        Target_TF = new javax.swing.JTextField();
        unit_label = new javax.swing.JLabel();
        unit_TF = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Name_TF = new javax.swing.JTextField();
        jCritical = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Code.setText("Code:");

        jLabel.setText("Label");

        label_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_TFActionPerformed(evt);
            }
        });

        Initials_label.setText("Initials");

        Skrill_label.setText("Skill");

        Capacity_label.setText("Capacity");

        allocation_label.setText("Allocation Mode");

        place_label.setText("Place");

        Standard_label.setText("Standard Rate");

        jLabel9.setText("euro");

        Overtime_label.setText("Overtime Rate");

        jLabel11.setText("euro");

        Use_label.setText("Use Cost");

        jLabel13.setText("euro");

        Target_label.setText("Target Group");

        Target_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Target_TFActionPerformed(evt);
            }
        });

        unit_label.setText("Unit");

        okButton.setText("ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("cancel");

        jLabel1.setText("Name");

        jCritical.setText("Critical");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_Code)
                        .addComponent(code_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_TF)
                        .addComponent(Initials_label)
                        .addComponent(Initials_TF)
                        .addComponent(Skrill_label)
                        .addComponent(Capacity_label)
                        .addComponent(Capacity_TF)
                        .addComponent(Skrill_TF))
                    .addComponent(allocation_label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(allocation_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(place_label)
                            .addComponent(place_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Standard_label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Standrad_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addComponent(jLabel1)
                            .addComponent(cancelButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unit_label)
                                    .addComponent(unit_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Use_label)
                                    .addComponent(Target_label)
                                    .addComponent(Target_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Overtime_TF)
                                            .addComponent(Name_TF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Overtime_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel11)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jCritical))
                                    .addComponent(Use_TF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Code)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(code_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Standard_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Standrad_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Initials_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Initials_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Capacity_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Capacity_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Skrill_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Skrill_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(allocation_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allocation_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(place_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(place_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Overtime_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Overtime_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(19, 19, 19)
                        .addComponent(Use_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Use_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCritical)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Target_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Target_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(unit_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unit_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_TFActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        String label = label_TF.getText();
        
        Long Capacity = null;
        try{
        Capacity=Long.valueOf(Capacity_TF.getText()).longValue();
        }
        catch(NumberFormatException e){
            
        }
        
        Long id = null;
        try{
        id=Long.valueOf(code_TF.getText()).longValue();
        }
        catch(NumberFormatException e){
            
        }
        Long standardRate = null;
        try{
        id=Long.valueOf(Standrad_TF.getText()).longValue();
        }
        catch(NumberFormatException e){
            
        }
        Long overtime = null;
        try{
        id=Long.valueOf(Overtime_TF.getText()).longValue();
        }
        catch(NumberFormatException e){
            
        }
        Long useCost = null;
        try{
        id=Long.valueOf(Use_TF.getText()).longValue();
        }
        catch(NumberFormatException e){
            
        }
        
        
        String initials = Initials_TF.getText();
        String skill = Skrill_TF.getText();
        String name = Name_TF.getText();
        String allocation = allocation_TF.getText();
        String place = place_TF.getText();
        String targetGroup = Target_TF.getText();
        String unit = unit_TF.getText();
        boolean critical=jCritical.isSelected();
        //Créer la ressource, créer l'élément DAO correspondant et le rajouter à la base.
        //HumanResource rh=  new HumanResource(id, code, name, initials, capacity, standardRate, overtimeRate, useCost, isCritical, skill, allocationMode, targetGroup, unit, place) {




        
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void Target_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Target_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Target_TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_RH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Capacity_TF;
    private javax.swing.JLabel Capacity_label;
    private javax.swing.JTextField Initials_TF;
    private javax.swing.JLabel Initials_label;
    private javax.swing.JTextField Name_TF;
    private javax.swing.JTextField Overtime_TF;
    private javax.swing.JLabel Overtime_label;
    private javax.swing.JTextField Skrill_TF;
    private javax.swing.JLabel Skrill_label;
    private javax.swing.JLabel Standard_label;
    private javax.swing.JTextField Standrad_TF;
    private javax.swing.JTextField Target_TF;
    private javax.swing.JLabel Target_label;
    private javax.swing.JTextField Use_TF;
    private javax.swing.JLabel Use_label;
    private javax.swing.JTextField allocation_TF;
    private javax.swing.JLabel allocation_label;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField code_TF;
    private javax.swing.JCheckBox jCritical;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Code;
    private javax.swing.JTextField label_TF;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField place_TF;
    private javax.swing.JLabel place_label;
    private javax.swing.JTextField unit_TF;
    private javax.swing.JLabel unit_label;
    // End of variables declaration//GEN-END:variables
}
